name: Minecleaner
version: '${project.version}-${git.commit.id.abbrev}'
author: LunarAkai
website: https://git.lunarakai.de/LunarAkai/NewMinecleaner
main: de.lunarakai.minecleaner.MinecleanerPlugin
api-version: '1.20'
depend:
  - CubesideUtils
softdepend: [CubesideSettings, PlayerUUIDCache]
commands:
  minecleaner:
    description: main command
    aliases: ["mcl", "minesweeper"]


permissions:
  minecleaner.admin: {}
  minecleaner.play: {}