name: Minecleaner
version: '${project.version}'
main: de.lunarakai.minecleaner.MinecleanerPlugin
api-version: '1.20'
commands:
  minecleaner:
    description: main command
    aliases: "mcl"


permissions:
  minecleaner.admin: {}
  minecleaner.play: {}