name: Minecleaner
version: '${project.version}'
author: LunarAkai
website: https://github.com/LunarAkai/Minecleaner
main: de.lunarakai.minecleaner.MinecleanerPlugin
api-version: '1.20'
commands:
  minecleaner:
    description: main command
    aliases: ["mcl", "minesweeper"]


permissions:
  minecleaner.admin: {}
  minecleaner.play: {}